### ISSUE TITLE
product recommendation plugin compatibility

### ISSUE THREAD

**Issue by ned-bs** [superspeedyplugins/issue-tracker#121]
**Describe the bug**
Product recommendation plugin recommends products based on some statistics.
https://woocommerce.com/products/product-recommendations/
After install Scalability Pro, it can't create any data for days.
It is probably because SPRO interfere queries. 

**To Reproduce**
I can provide staging environment. 

**Expected behavior**
SPRO + Product recommendation work together

**Comment by ned-bs** [comment]
These errors are probably related with same issue.

```
WordPress database error MySQL server has gone away for query SELECT SQL_CALC_FOUND_ROWS wp_posts.ID
FROM wp_posts LEFT JOIN wp_term_relationships AS tr ON (wp_posts.ID = tr.object_id) LEFT JOIN wp_term_relationships AS tr1 ON (wp_posts.ID = tr1.object_id) INNER JOIN wp_postmeta AS meta2 ON (wp_posts.ID = meta2.post_id)
WHERE 1=1 AND wp_posts.post_type IN ('product', 'product_variation') AND ((wp_posts.post_status <> 'trash' AND wp_posts.post_status <> 'auto-draft')) AND (tr.term_taxonomy_id IN (739) OR tr1.term_taxonomy_id IN (118) OR meta2.meta_key = '_stock_status' AND meta2.meta_value != 'eol') AND wp_posts.post_type = 'product' AND wp_posts.ID NOT IN (SELECT o.ID FROM wp_posts o
LEFT OUTER JOIN wp_posts r
ON o.post_parent = r.ID
WHERE r.post_status = 'trash' AND o.post_type = 'product_variation')
OR (wp_posts.post_type = 'product_variation' AND wp_posts.post_status <> 'trash'


AND wp_posts.post_parent IN (
SELECT DISTINCT wp_posts.ID
FROM wp_posts LEFT JOIN wp_term_relationships AS tr ON (wp_posts.ID = tr.object_id) LEFT JOIN wp_term_relationships AS tr1 ON (wp_posts.ID = tr1.object_id) INNER JOIN wp_postmeta AS meta2 ON (wp_posts.ID = meta2.post_id)
WHERE wp_posts.post_type = 'product' AND ((wp_posts.post_status <> 'trash' AND wp_posts.post_status <> 'auto-draft')) AND (tr.term_taxonomy_id IN (739) OR tr1.term_taxonomy_id IN (118) OR meta2.meta_key = '_stock_status' AND meta2.meta_value != 'eol')
)

OR wp_posts.ID IN (
SELECT DISTINCT wp_posts.ID
FROM wp_posts LEFT JOIN wp_term_relationships AS tr ON (wp_posts.ID = tr.object_id) LEFT JOIN wp_term_relationships AS tr1 ON (wp_posts.ID = tr1.object_id) INNER JOIN wp_postmeta AS meta2 ON (wp_posts.ID = meta2.post_id)
WHERE wp_posts.post_type = 'product_variation' AND ((wp_posts.post_status <> 'trash' AND wp_posts.post_status <> 'auto-draft')) AND (tr.term_taxonomy_id IN (739) OR tr1.term_taxonomy_id IN (118) OR meta2.meta_key = '_stock_status' AND meta2.meta_value != 'eol') )


) GROUP BY wp_posts.ID

ORDER BY wp_posts.ID ASC
LIMIT 0, 50 made by require_once('/srv/htdocs/wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, pmxe_wp_loaded, PMXE_Export_Record->execute, WP_Query->__construct, WP_Query->query, WP_Query->get_posts
```

**Other error**
```
WordPress database error MySQL server has gone away for query SELECT SQL_CALC_FOUND_ROWS wp_posts.ID
FROM wp_posts LEFT JOIN wp_term_relationships AS tr ON (wp_posts.ID = tr.object_id) LEFT JOIN wp_term_relationships AS tr1 ON (wp_posts.ID = tr1.object_id) INNER JOIN wp_postmeta AS meta2 ON (wp_posts.ID = meta2.post_id)
WHERE 1=1 AND wp_posts.post_type IN ('product', 'product_variation') AND ((wp_posts.post_status <> 'trash' AND wp_posts.post_status <> 'auto-draft')) AND (tr.term_taxonomy_id IN (739) OR tr1.term_taxonomy_id IN (118) OR meta2.meta_key = '_stock_status' AND meta2.meta_value != 'eol') AND wp_posts.post_type = 'product' AND wp_posts.ID NOT IN (SELECT o.ID FROM wp_posts o
LEFT OUTER JOIN wp_posts r
ON o.post_parent = r.ID
WHERE r.post_status = 'trash' AND o.post_type = 'product_variation')
OR (wp_posts.post_type = 'product_variation' AND wp_posts.post_status <> 'trash'


AND wp_posts.post_parent IN (
SELECT DISTINCT wp_posts.ID
FROM wp_posts LEFT JOIN wp_term_relationships AS tr ON (wp_posts.ID = tr.object_id) LEFT JOIN wp_term_relationships AS tr1 ON (wp_posts.ID = tr1.object_id) INNER JOIN wp_postmeta AS meta2 ON (wp_posts.ID = meta2.post_id)
WHERE wp_posts.post_type = 'product' AND ((wp_posts.post_status <> 'trash' AND wp_posts.post_status <> 'auto-draft')) AND (tr.term_taxonomy_id IN (739) OR tr1.term_taxonomy_id IN (118) OR meta2.meta_key = '_stock_status' AND meta2.meta_value != 'eol')
)

OR wp_posts.ID IN (
SELECT DISTINCT wp_posts.ID
FROM wp_posts LEFT JOIN wp_term_relationships AS tr ON (wp_posts.ID = tr.object_id) LEFT JOIN wp_term_relationships AS tr1 ON (wp_posts.ID = tr1.object_id) INNER JOIN wp_postmeta AS meta2 ON (wp_posts.ID = meta2.post_id)
WHERE wp_posts.post_type = 'product_variation' AND ((wp_posts.post_status <> 'trash' AND wp_posts.post_status <> 'auto-draft')) AND (tr.term_taxonomy_id IN (739) OR tr1.term_taxonomy_id IN (118) OR meta2.meta_key = '_stock_status' AND meta2.meta_value != 'eol') )


) GROUP BY wp_posts.ID

ORDER BY wp_posts.ID ASC
LIMIT 0, 50 made by require_once('/srv/htdocs/wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, pmxe_wp_loaded, PMXE_Export_Record->execute, WP_Query->__construct, WP_Query->query, WP_Query->get_posts
```

**Comment by voodoo911** [comment]
@ned-bs Sent you message via Discord

**Comment by ned-bs** [comment]
replied by video.
Error messages shown in error.log files.
Also SPRO brokes queries like best selling products etc. Thus Product recommendation plugin can't recommend right products

**Comment by voodoo911** [comment]
@dhilditch Sent you a message in discord

**Comment by ned-bs** [comment]
hi,
Should I expect a solution for this case soon?
Thanks

**Comment by ned-bs** [comment]
Hi there, any feedback?

**Comment by voodoo911** [comment]
Waiting for @dhilditch

**Comment by betayazilim** [comment]
Sure

**Comment by dhilditch** [comment]
Compatibility added in 5.59

**Comment by betayazilim** [comment]
Hi,
based on our talk;
It is solved for all time selection.
Issue is continue when set the engine with time frame like 3 months.

when SPRO is off, it works
When all time instead of 3 months, it works,

~wondering if this is from spro changing a left join to an inner join`

**Comment by dhilditch** [comment]
This has been reported partially fixed, need to check inner join under wp cron, he says last 3 months fails but if he does all data it works

**Comment by dhilditch** [comment]
Checked against Scalability Pro 6.26.7. Version 5.59 added the Product Recommendations compatibility path, but the follow-up report for the three-month timeframe is not addressed in the changelog or current special case. Suggested fix: include the timeframe-specific query shape in the cache key and add a regression test for all-time versus three-month recommendations.
