### ISSUE TITLE
Cannot turn off Meta Pagination Tags in SSF. Yoast SEO compatibility Problem

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#142]
**PLEASE COMPLETE ALL STEPS TO SPEED UP BUG FIXES**

1. Super Speedy Filters > SEO & Indexing > Meta Pagination Tags
2. This setting is stuck on ALL. No matter what you change it to, redis and caches cleared, it wont change to multi-term or disabled.
3. This causes an SEO problem and a clash with yoast - Yoast already inserts this data in the Yoast meta data section.

Please can you investigate and confirm why I cannot turn this off or set it to multi-term

**Comment by dhilditch** [comment]
@thinkjarvisdesignandmarketing I investigate this and found the opposite to be true. I found that the ALL option was not working at all i.e. for single terms like /product-category/clothing/ my code was not running.

Can you confirm?

**Comment by thinkjarvisdesignandmarketing** [comment]
The other options on multiterm removes the meta data.

This one: see screenshot. If I change this one and click save, it doesnt save the changes so it is still set on all.

![image](https://github.com/superspeedyplugins/issue-tracker/assets/54110498/0ac61da8-2c7d-485f-8743-059c83be61d3)

With the others set to multi-term it seems to remove the duplicated meta data so only Yoasts data is present.

**Comment by thinkjarvisdesignandmarketing** [comment]
I can give you a WP login for this site over discord if you want to try it your end?

**Comment by thinkjarvisdesignandmarketing** [comment]
Just had a look. I cannot change the meta pagination tags option still - however on the site below it is no longer adding the meta pagination tags a second time after yoast has already added them.

https://www.wall2floordesign.co.uk/product-category/flooring/herringbone-vinyl-tile-flooring/

**Comment by thinkjarvisdesignandmarketing** [comment]
@dhilditch Any update on this one?

**Comment by dhilditch** [comment]
Fixed in 5.75

**Comment by thinkjarvisdesignandmarketing** [comment]
@dhilditch 
I am still getting issues with pagination.
My pagination now looks like this upon scroll:

![image](https://github.com/superspeedyplugins/issue-tracker/assets/54110498/f68023b5-eea8-4763-82bb-5a7697dcba85)

**Comment by thinkjarvisdesignandmarketing** [comment]
The issue is here:
![image](https://github.com/superspeedyplugins/issue-tracker/assets/54110498/a7802734-8737-49b1-8334-2c963edf561c)

When remove SQL_CALC_ROWS on front end is set to ON. It sets the max pagination to 100 which will almost always be a 404 error. If I keep SQL_CALC_ROWS it corrects the max pagination.

Can I suggest that the remove SQL_CALC_ROWS actually removes the >> button so there is no link at all to the max pagination for a category?

I'll raise a new ticket for this

**Comment by thinkjarvisdesignandmarketing** [comment]
![image](https://github.com/superspeedyplugins/issue-tracker/assets/54110498/f73034d7-19e7-4567-b222-ffd0fb7984fd)

**Comment by thinkjarvisdesignandmarketing** [comment]
@dhilditch 
I still cannot change this value. But the SSF prev and next link= entries are no longer there.

The yoast pagination is only correct on the first load of the category. This means with Auto Infinite Scroll enabled the Yoast Pagination is always wrong. Sorry about this, an oversight on my part. It is technically correct for the first page but it means that when you scroll it doesnt update to include a next and prev button. I dont think this is a major problem from an SEO perspective as paginated pages are set to no index, follow.

I'll re run the audit for this issue and let you know what it suggests.
