### ISSUE TITLE
Broken guide link from SSS Main tab

### ISSUE THREAD

**Issue by dhilditch** [superspeedyplugins/issue-tracker#222]
No description provided.

Additional Context:
Replied to message: https://discord.com/channels/837258064704438282/880086738159149067/1296119564467441765

thaan_: <@828660546823913473> Small URL that doesn't work, this link goes to https://www.superspeedyplugins.com/knowledgebase/enabled/ which doesn't work

**Comment by Glynnage** [comment]
Fixed in https://github.com/superspeedyplugins/super-speedy-search/tree/222-broken-guide-link-from-sss-main-tab

- Added conditional logic to remove the "Read full guide" link in the tooltip for settings overridden via wp-config.php and data deletion on deactivation.

**Comment by dhilditch** [comment]
Checked SSS 5.58. The broken URL is still present in assets/js/context-help.js as /knowledgebase/enabled/. Suggested fix: replace it with the current SSS main-tab guide URL and add a lightweight link check for contextual-help URLs.
