### ISSUE TITLE
Urgent: PCI failure due to XSS / Script Injection issues still present in SSF

### ISSUE THREAD

**Issue by thinkjarvisdesignandmarketing** [superspeedyplugins/issue-tracker#288]
**PLEASE COMPLETE ALL STEPS TO SPEED UP BUG FIXES**

Refer to previous issue
https://github.com/superspeedyplugins/issue-tracker/issues/253

Part 1:
SSF If you enable ALL in the meta SEO features for any of the options - It does not escape the HTML - Allowing scripts to be inserted on any shop page or any option with ALL selected.

As a temp fix changing this to multi-term seems to escape the HTML correctly preventing script injection.

Please check all options in meta seo features for this problem.

Part 2:
When the price filter widget is enabled - The price filter url can be injected with executables.

Example
/?minprice=<script%20src%3Dhttp%3A%2F%2Flocalhost%2Fj%20
Our wordfence system does block the execution of this but it is still a PCI fail. Without a firewall the code can be successfully injected

Part 3:
We previously raised an issue with XSS where the active filters widget was allowing script injection. This issue is occuring again even when price filter is disabled.
https://github.com/superspeedyplugins/issue-tracker/issues/253

Please escape the output properly to prevent script injection.

Part 4:
If you put in any URL structure from the shop. It will allow anything to be written after the actual shown category and it still loads. It should 404?

Attribute called brands NOT the new Woo Brand default.
/brands/linniepink/ - Correct
/brands/linniepink/twgsggg/ - Should 404 but doesnt?
/downloads/frostyreflections/ - Correct
/downloads/frostyreflections/wp0tgjsgr/  - Should 404 but doesnt?

Adding anything to the end of the filters still displays the results which it shouldnt - Please can you rectify this to prevent injections of code and URLs.

**IMPORTANT CONTEXT**

I have private messaged you the PCI report.

If you need the lastest copy from our most recent scan please let me know and I will private message you more on discord.

**Comment by dhilditch** [comment]
Ok - I'll get these fixed this week as priority - re: number 4, we did have an option for these to redirect to the correct URL. I'll dig that out and resurrect it and add the option to either do nothing, 404 or 301.

**Comment by thinkjarvisdesignandmarketing** [comment]
Yeah sure thanks David,

Re number 4: This is a problem for both speed and performance and security. It must loop back to a 404 of some kind otherwise the queries will still run? Correct me if I am wrong?
Bots hitting those URLs will also cause queries to take place.

**Comment by thinkjarvisdesignandmarketing** [comment]
@dhilditch How are you getting on with this?

Part 1-3:
We managed to get a PCI pass by disabling the multi-term option, removing the current filters widget, disabled the price widget.

Part 4 in my request:
To help control google's activity on our sites we have implimented an outright block on certain url strings using mod_security. Code below:
SecRule REQUEST_URI "(?i)^/my-account/lost-password/tel(%3A|:)" \
"id:100001,phase:1,deny,status:403,log,msg:'Blocked tel: URI in lost password'"

SecRule REQUEST_URI "(?i)avia_extended_shop_select" \
"id:100002,phase:1,deny,status:403,log,msg:'Blocked avia_extended_shop_select in URI'"

SecRule ARGS_NAMES "(?i)^query_type_product-type$" \
"id:100003,phase:2,deny,status:403,log,msg:'Blocked query_type_product-type parameter'"

The first one is specific to a DOS attack on one website. The other 2 relate to enfold filters which we had to disable due to abuse. We reported the problem to Enfold and they have re-written their filters so the URLs are hidden. However because the bots are stuck crawling the strings for the past 12 months+ Google and Bing STILL continue to crawl the query strings - Hence the block.

These changes above have a significant impact on server resource usage. Google and Bing were contributing to our mysql memory and phpfpm spiking so worth noting that it is worth checking what the bots are actually crawling to ensure they arent causing the server to become bogged down.

**Comment by thinkjarvisdesignandmarketing** [comment]
How are we looking for a fix to the 4 issues raised Dave?

**Comment by dhilditch** [comment]
Part 4 fixed in 6.19

**Comment by dhilditch** [comment]
Part 1 - I found the browser title did not have any escaping function, I've added that.

**Comment by dhilditch** [comment]
I cannot replicate part 2. I presume that for this to work, the 'Show Existing Filters' widget has to be enabled otherwise the paramater value would never be displayed, but in any case, all parameters go through this function:

            $sanitized = $this->sanitizeParameter($value);

This returns null for anything with HTML parameters or script in it so then that parameter is just completely ignored.

**Comment by dhilditch** [comment]
To clarify, with part 2, URLs such as:

https://localhost/product-category/hardware/?minprice=%3Cscript%3Ealert(%27vulnerable!%27)%3C/script%3E

can be loaded, but nothing bad actually happens and this parameter is completely ignored by the SuperSpeedyPermalink class.

**Comment by dhilditch** [comment]
Fixed in 6.19

**Comment by thinkjarvisdesignandmarketing** [comment]
THanks David,

I'll ask the client to re-enable the settings and request another PCI scan with their provider.

Will let you know if we still see a failure.
