### ISSUE TITLE
SSF | 'Show in stock' not working. 

### ISSUE THREAD

**Issue by RexHavoc69** [superspeedyplugins/issue-tracker#30]
**Describe the bug**
'Show in stock' when selected still shows out of stock items.

**To Reproduce**
Select a category or perform a search and then apply the 'Show in stock' filter.

**Expected behavior**
Should only show in stock items.

**Screenshots**
![image](https://github.com/superspeedyplugins/issue-tracker/assets/92769963/36c0539d-6c63-451c-b3bb-1818dba70d44)

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
Im fairly certain this issue was resolved once before?

**Comment by dhilditch** [comment]
This was fixed in 5.15. For performance reasons, I fixed this through the object_ancestors table so this means a table rebuild is required in order to see the new functionality.

**Comment by RexHavoc69** [comment]
Unfortunately for our website it isnt resolved. Running 5.16 and have rebuilt the ancestors table.
